FROM golang:1.16-alpine AS builder

# Move to working directory (/build).
WORKDIR /rmq-messenger

# Copy and download dependency using go mod.
COPY go.mod ./
RUN apk update
RUN apk add git
RUN go mod tidy

# Copy the code into the container.
COPY ./send.go .

# Set necessary environment variables needed 
# for our image and build the sender.
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o send send.go 

FROM alpine

# Copy binary and config files from /build 
# to root folder of scratch container.
COPY --from=builder /rmq-messenger/send .

# Command to run when starting the container.
CMD ["/rmq-messenger/send"]
